psteinroe/supabase-cache-helpers

package.json, packages/postgrest-swr/README.md
- fix docs for postgrest-swr
- add reset-git and clear-branches scripts
=> chore: docs and helper scripts

packages/eslint-config-custom/package.json, packages/jest-presets/package.json, packages/postgrest-fetcher/package.json, packages/postgrest-filter/package.json, packages/postgrest-mutate/package.json, packages/postgrest-shared/package.json, packages/postgrest-swr/__tests__/mutate/use-delete-mutation.integration.spec.tsx, packages/postgrest-swr/__tests__/mutate/use-insert-mutation.integration.spec.tsx, packages/postgrest-swr/__tests__/mutate/use-update-mutation.integration.spec.tsx, packages/postgrest-swr/__tests__/mutate/use-upsert-mutation.integration.spec.tsx, packages/postgrest-swr/__tests__/query/use-counted-pagination.integration.spec.tsx, packages/postgrest-swr/__tests__/query/use-infinite-query.integration.spec.tsx, packages/postgrest-swr/__tests__/query/use-infinite-scroll-query.integration.spec.tsx, packages/postgrest-swr/__tests__/query/use-pagination-query.integration.spec.tsx, packages/postgrest-swr/__tests__/query/use-query.integration.spec.tsx, packages/postgrest-swr/package.json, packages/tsconfig/package.json
https://github.com/renovatebot/renovate/issues/4724
=> fix: renovate changelog generation

.changeset/silver-chairs-cry.md, packages/postgrest-swr/src/lib/remove.ts
=> fix: remove filter check when removing

.changeset/short-rockets-obey.md, packages/postgrest-mutate/__tests__/update.spec.ts, packages/postgrest-mutate/__tests__/upsert.spec.ts, packages/postgrest-mutate/package.json, packages/postgrest-mutate/src/insert.ts, packages/postgrest-mutate/src/lib/calculate-new-count.ts, packages/postgrest-mutate/src/update.ts, packages/postgrest-mutate/src/upsert.ts, packages/postgrest-swr/src/lib/update.ts, packages/postgrest-swr/src/lib/upsert.ts, pnpm-lock.yaml, turbo.json
=> fix: properly handle an invalid item after it was updated

.changeset/great-dolls-build.md, packages/postgrest-fetcher/__tests__/lib/load-query.spec.ts, packages/postgrest-fetcher/__tests__/lib/mutation-response.spec.ts, packages/postgrest-fetcher/src/lib/load-query.ts, packages/postgrest-fetcher/src/lib/mutation-response.ts, packages/postgrest-filter/__tests__/lib/parse-select-param.spec.ts, packages/postgrest-filter/__tests__/lib/transform-recursive.spec.ts, packages/postgrest-filter/src/lib/index.ts, packages/postgrest-filter/src/lib/transform-recursive.ts, packages/postgrest-filter/src/postgrest-filter.ts
- fix loadQuery and mutation response to properly work with nested relations and aliases
- refactor similar logic to be able to share more
=> fix loadQuery and mutation response

.changeset/neat-teachers-begin.md, packages/postgrest-swr/__tests__/query/use-pagination-query.integration.spec.tsx, packages/postgrest-swr/src/query/use-pagination-query.ts
=> fix: setPage() when page is not loaded already

.changeset/slimy-clouds-walk.md, docs/pages/postgrest/subscriptions.mdx, packages/postgrest-react-query/__tests__/subscribe/use-subscription.integration.spec.tsx, packages/postgrest-react-query/src/subscribe/use-subscription.ts, packages/postgrest-swr/__tests__/subscribe/use-subscription.integration.spec.tsx, packages/postgrest-swr/src/subscribe/use-subscription.ts
=> fix: refactor useSubscription to create the channel internally

.changeset/moody-plums-try.md, packages/postgrest-fetcher/src/delete.ts, packages/postgrest-fetcher/src/insert.ts, packages/postgrest-fetcher/src/update.ts, packages/postgrest-fetcher/src/upsert.ts, packages/postgrest-react-query/src/mutate/types.ts, packages/postgrest-react-query/src/mutate/use-delete-mutation.ts, packages/postgrest-react-query/src/mutate/use-insert-mutation.ts, packages/postgrest-react-query/src/mutate/use-update-mutation.ts, packages/postgrest-react-query/src/mutate/use-upsert-mutation.ts, packages/postgrest-swr/src/mutate/types.ts, packages/postgrest-swr/src/mutate/use-delete-mutation.ts, packages/postgrest-swr/src/mutate/use-insert-mutation.ts, packages/postgrest-swr/src/mutate/use-update-mutation.ts, packages/postgrest-swr/src/mutate/use-upsert-mutation.ts
=> fix: expose mutation options from supabase sdk

.changeset/soft-birds-brush.md, examples/react-query/types/database.ts, examples/swr/types/database.ts, package.json, packages/postgrest-fetcher/__tests__/database.types.ts, packages/postgrest-fetcher/src/delete.ts, packages/postgrest-fetcher/src/insert.ts, packages/postgrest-fetcher/src/pagination-fetcher.ts, packages/postgrest-fetcher/src/update.ts, packages/postgrest-fetcher/src/upsert.ts, packages/postgrest-filter/__tests__/database.types.ts, packages/postgrest-react-query/src/mutate/use-delete-mutation.ts, packages/postgrest-react-query/src/mutate/use-insert-mutation.ts, packages/postgrest-react-query/src/mutate/use-update-mutation.ts, packages/postgrest-react-query/src/mutate/use-upsert-mutation.ts, packages/postgrest-swr/__tests__/database.types.ts, packages/postgrest-swr/src/mutate/use-delete-mutation.ts, packages/postgrest-swr/src/mutate/use-insert-mutation.ts, packages/postgrest-swr/src/mutate/use-update-mutation.ts, packages/postgrest-swr/src/mutate/use-upsert-mutation.ts, packages/postgrest-swr/src/query/use-infinite-query.ts, packages/postgrest-swr/src/query/use-infinite-scroll-query.ts, packages/postgrest-swr/src/subscribe/use-subscription-query.ts
=> fix: relationship types

docs/pages/postgrest/queries.mdx, docs/pages/postgrest/ssr/react-query.mdx
This PR fixes some typos found in the documentation
=> fix: typos

.changeset/stupid-grapes-exist.md, packages/postgrest-react-query/src/query/build-query-opts.ts, packages/postgrest-react-query/src/query/fetch.ts, packages/postgrest-react-query/src/query/index.ts, packages/postgrest-react-query/src/query/prefetch.ts, packages/postgrest-react-query/src/query/use-query.ts
=> feat: export buildQueryOptions and fetchQuery wrapper

.changeset/rotten-pillows-eat.md, packages/postgrest-core/__tests__/delete-fetcher.spec.ts, packages/postgrest-core/src/delete-fetcher.ts, packages/postgrest-react-query/__tests__/mutate/use-delete-many-mutation.integration.spec.tsx, packages/postgrest-react-query/package.json, packages/postgrest-react-query/src/mutate/index.ts, packages/postgrest-react-query/src/mutate/types.ts, packages/postgrest-react-query/src/mutate/use-delete-many-mutation.ts, packages/postgrest-swr/__tests__/mutate/use-delete-many-mutation.spec.tsx, packages/postgrest-swr/package.json, packages/postgrest-swr/src/mutate/index.ts, packages/postgrest-swr/src/mutate/types.ts, packages/postgrest-swr/src/mutate/use-delete-many-mutation.ts
we can replace useDeleteMutation with useDeleteManyMutation and drop useDeleteManyMutation in the next major release
closes #348
=> feat: add delete many mutation

.changeset/three-spiders-work.md, packages/postgrest-react-query/__tests__/query/fetch.spec.ts, packages/postgrest-react-query/src/query/fetch.ts
=> fix: actually return from fetch query

.changeset/stale-ads-remember.md, packages/postgrest-core/__tests__/lib/get.spec.ts, packages/postgrest-core/__tests__/lib/parse-order-by-key.spec.ts, packages/postgrest-core/__tests__/lib/sorted-comparator.spec.ts, packages/postgrest-core/src/lib/get.ts
Add support for parsing and using JSON columns for order statements.
Fixes #442
=> fix: correctly parse and sort using JSON expressions

.changeset/small-trainers-flow.md, packages/postgrest-react-query/__tests__/subscribe/use-subscription-query.integration.spec.tsx, packages/postgrest-react-query/__tests__/subscribe/use-subscription.integration.spec.tsx, packages/postgrest-react-query/src/subscribe/use-subscription-query.ts, packages/postgrest-swr/__tests__/subscribe/use-subscription-query.integration.spec.tsx, packages/postgrest-swr/__tests__/subscribe/use-subscription.integration.spec.tsx, packages/postgrest-swr/src/subscribe/use-subscription-query.ts
=> Fix use subscription query deletes

.changeset/ten-otters-vanish.md, .changeset/tricky-donuts-do.md, package.json, packages/postgrest-core/__tests__/index.spec.ts, packages/postgrest-core/src/index.ts, packages/postgrest-core/src/lib/is-postgrest-transform-builder.ts, packages/postgrest-react-query/src/query/build-query-opts.ts, pnpm-lock.yaml
=> feat: support abort signal in react query

.changeset/spotty-trains-attend.md, packages/postgrest-core/src/lib/parse-select-param.ts, packages/postgrest-core/src/lib/query-types.ts, packages/postgrest-core/src/mutate-item.ts, packages/postgrest-core/src/postgrest-filter.ts, packages/postgrest-core/src/upsert-item.ts, packages/postgrest-core/tests/lib/parse-select-param.spec.ts, packages/postgrest-core/tests/mutate-item.spec.ts, packages/postgrest-core/tests/postgrest-filter.spec.ts, packages/postgrest-core/tests/upsert-item.spec.ts, packages/postgrest-react-query/tests/mutate/use-update-mutation.integration.spec.tsx, packages/postgrest-swr/tests/mutate/use-update-mutation.integration.spec.tsx, supabase/migrations/20240311151147_allow_aggregates.sql
=> feat: support aggregates

.changeset/grumpy-rice-chew.md, packages/postgrest-core/src/index.ts, packages/postgrest-core/src/lib/parse-order-by.ts, packages/postgrest-core/src/postgrest-parser.ts, packages/postgrest-core/tests/index.spec.ts
=> feat: export parse order by helper

.changeset/tiny-bottles-wave.md, packages/postgrest-core/src/postgrest-filter.ts, packages/postgrest-core/tests/postgrest-filter.spec.ts
=> fix(postgrest-core): handle nested arrays properly

.changeset/sad-walls-notice.md, packages/storage-core/src/upload.ts, packages/storage-core/tests/upload.spec.ts
=> feat: useUpload to support file metadata
