psteinroe/supabase-cache-helpers

.changeset/olive-squids-flow.md
packages/postgrest-fetcher/package.json
packages/postgrest-filter/package.json
packages/postgrest-mutate/package.json
packages/postgrest-react-query/package.json
packages/postgrest-shared/package.json
packages/postgrest-swr/package.json
packages/storage-fetcher/package.json
packages/storage-mutate/package.json
packages/storage-react-query/package.json
packages/storage-swr/package.json

When using `moduleResolution` other then old `node` (node16, nodenext, bundler) there is a TS error:
```
Could not find a declaration file for module '@supabase-cache-helpers/postgrest-react-query'.
There are types at 'node_modules/@supabase-cache-helpers/postgrest-react-query/dist/index.d.ts', but this result could not be resolved when respecting package.json "exports". The '@supabase-cache-helpers/postgrest-react-query' library may need to update its package.json or typings.
```
Here is more context https://github.com/egoist/tsup/issues/760#issuecomment-1451112010

Fix types for mjs

---

.changeset/shy-islands-breathe.md
packages/postgrest-swr/package.json
packages/postgrest-swr/src/lib/middleware.ts
packages/postgrest-swr/src/mutate/types.ts
packages/postgrest-swr/src/mutate/use-delete-mutation.ts
packages/postgrest-swr/src/mutate/use-insert-mutation.ts
packages/postgrest-swr/src/mutate/use-update-mutation.ts
packages/postgrest-swr/src/mutate/use-upsert-mutation.ts
packages/postgrest-swr/src/query/use-query.ts
pnpm-lock.yaml

fix: swr types

---

.changeset/early-seals-rush.md
packages/postgrest-react-query/src/index.ts

The postgrest-react-query package is currently missing some exports mentioned in the docs (e.g. useUpsertItem, useDeleteItem). I've adjusted them so that they are identical to postgrest-swr's ones.

Fix missing exports in postgrest-react-query

---

docs/pages/postgrest/custom-cache-updates.mdx
docs/pages/postgrest/getting-started.mdx
docs/pages/postgrest/subscriptions.mdx

- Fix `useUpsertItem` examples in `postgrest/custom-cache-updates`
- Update `postgrest/getting-started` to reflect refactored subscription hooks & guide towards naming channels
- Update `postgrest/subscriptions` to guide unique channel naming

Fix docs to improve guidance on subscription hooks usage

---

.changeset/small-keys-protect.md
packages/postgrest-core/__tests__/mutate/transformers.spec.ts
packages/postgrest-core/__tests__/upsert-item.spec.ts
packages/postgrest-core/src/mutate/transformers.ts

has been set to `undefined` before

fix: set hasMore to false if list is currently empty

---

.changeset/clean-rings-laugh.md
package.json
packages/postgrest-react-query/src/mutate/types.ts
packages/postgrest-react-query/src/query/use-query.ts
packages/postgrest-swr/src/mutate/types.ts
packages/postgrest-swr/src/query/use-query.ts

This PR exports the packages types so that developers can use it in their projects
Related issue: https://github.com/psteinroe/supabase-cache-helpers/issues/350

Export types and interfaces

---

.changeset/big-gorillas-train.md
docs/pages/postgrest/ssr/swr.mdx
packages/postgrest-swr/package.json
packages/postgrest-swr/src/index.react-server.ts
packages/postgrest-swr/tsup.config.ts
pnpm-lock.yaml

References https://github.com/psteinroe/supabase-cache-helpers/issues/261#issuecomment-1850167194

Add react-server export support for postgrest-swr package and edit docs

---

.changeset/rude-glasses-battle.md
packages/postgrest-swr/__tests__/mutate/use-update-mutation.integration.spec.tsx
packages/postgrest-swr/src/cache/use-delete-item.ts
packages/postgrest-swr/src/cache/use-mutate-item.ts
packages/postgrest-swr/src/cache/use-upsert-item.ts

when splitting mutate and revalidate, I forgot to pass the key to `mutate`. this pr fixes this and adds a test.
fixes #365

fix: make revalidate relations and table work again

---

.changeset/stale-owls-compete.md
examples/react-query/package.json
package.json
packages/postgrest-core/__tests__/delete-fetcher.spec.ts
packages/postgrest-core/src/delete-fetcher.ts
packages/postgrest-core/src/delete-item.ts
packages/postgrest-core/src/upsert-item.ts
pnpm-lock.yaml

thanks to the great prep of @Keithcat767, this actually uncovered two bugs:
1. when re-implementing the fetchers during the last big refactor, i somehow thought it would be a good idea to just return the primary keys from the delete fetcher. Turns out it isnt, because we may need more than the pks to handle revalidateRelation properly! this pr applies the same logic as with the other fetchers and properly builds the query and parses the results.
2. when checking for revalidate relations, we were passing the transformedInput. this is wrong, because for revalidate relations the cache key we are currently looking at is not from the same relation as our input. so transforming doesnt make any sense. we now just pass the input.

fixes #390

---

docs/package.json
examples/react-query/package.json
examples/swr/package.json
packages/eslint-config-custom/package.json
packages/postgrest-core/package.json
packages/postgrest-react-query/package.json
packages/postgrest-swr/package.json
packages/storage-core/package.json
packages/storage-react-query/package.json
packages/storage-swr/package.json
pnpm-lock.yaml

Hi there! This should close #401  and #405 (please refer to my breakdown in #401 for more context)
I discovered a similar issue with Tanstack Query and the resolution was updating Typescript to the latest stable version v5.4.2. 
https://github.com/TanStack/query/issues/6318
After updating and building this package, typesafety was restored with moduleResolution bundler. I think we got pretty lucky with the timing here since this update from TS was just released! 
For parity, I went ahead and matched all TS versions in all packages, I hope that's okay. Other than that...this was quite an easy fix after staring at it for a second!

updates typescript to v5.4.2

---

.changeset/real-pants-stare.md
packages/postgrest-swr/src/cache/use-delete-item.ts
packages/postgrest-swr/src/cache/use-mutate-item.ts
packages/postgrest-swr/src/cache/use-upsert-item.ts

passing `data` causes the query to be set to `undefined` until the new
data arrives.
cant see a way to apply the options [as per swr docs](https://swr.vercel.app/docs/mutation.en-US#revalidation) or types of the
function.
fixes #467

fix: use only `mutate(key)` for revalidation

---

packages/postgrest-swr/__tests__/mutate/use-update-mutation.integration.spec.tsx

tests for https://github.com/psteinroe/supabase-cache-helpers/pull/468
Fails before patch, and passes after.
Maybe you'd like to test differently, but used the same technique as in the repro repo and it's rather simple.

fix: add test for revalidation undefined

---

.changeset/lazy-bananas-tap.md
packages/postgrest-core/src/lib/parse-select-param.ts
packages/postgrest-core/tests/lib/parse-select-param.spec.ts

Fixes #437
Also modifies `parse-select-param.spec.ts` special case test to have two embeddings back-to-back.

fix: select param parsing when embedding begins with another embedding

---

docs/pages/configuration.mdx

I believe there is a typo in the JSX syntax, which is causing the syntax highlighting to break

Fix JSX typo in configuration.mdx

---

.changeset/tame-planes-report.md
packages/postgrest-react-query/src/query/use-query.ts

PR for #514 
Omit<UseReactQueryResult<...>> caused the union in UseReactQueryResult to dissolve, I added a helper for distributive application of Omit to preserve it.
With the union back, the body / return of useQuery also needed some adjustment to cover the different cases. It's a bit more verbose this way, but also a bit more explicit :)

fix: allow useQuery (react-query version) to return a union

---

.changeset/six-timers-turn.md
packages/postgrest-core/src/update-fetcher.ts
packages/postgrest-core/tests/update-fetcher.spec.ts

Fix #517 by replacing falsy check by strict `null` & `undefined` validation

:bug: improve primary key value validation in update fetcher

---

.changeset/moody-lobsters-juggle.md
examples/react-query/package.json
examples/swr/package.json
packages/postgrest-core/package.json
packages/postgrest-react-query/package.json
packages/postgrest-react-query/src/mutate/types.ts
packages/postgrest-server/package.json
packages/postgrest-swr/package.json
packages/storage-core/package.json
packages/storage-react-query/package.json
packages/storage-swr/package.json
pnpm-lock.yaml

fixes #509 
@damien-schneider note that supabase recently reverted the postgrest version used in `supabase-js` due to typing issues. make sure to install the package versions that are listed in the `package.json` of `supabase-js`

chore: update to latest supabase-js

---

docs/components/linked-tabs.tsx
docs/components/tab-context.tsx
docs/pages/_app.tsx
docs/pages/configuration.mdx
docs/pages/postgrest/custom-cache-updates.mdx
docs/pages/postgrest/getting-started.mdx
docs/pages/postgrest/mutations.mdx
docs/pages/postgrest/queries.mdx
docs/pages/postgrest/server.mdx
docs/pages/postgrest/subscriptions.mdx
docs/pages/storage/getting-started.mdx
docs/pages/storage/mutations.mdx
docs/pages/storage/queries.mdx

This pull request introduces a new `LinkedTabs` component and integrates it across various documentation files to enhance tab functionality. The changes include the creation of the `LinkedTabs` component, the `TabContext` for managing tab state, and updating the documentation pages to use the new component.
* [`docs/components/linked-tabs.tsx`](diffhunk://#diff-1050986087fe977d1acf4acd32b1bdc5bdd0f32154021976f5281f91ae8a7bb8R1-R31): Added the `LinkedTabs` component to manage tab selection and state using the `useTabContext` hook.
* [`docs/components/tab-context.tsx`](diffhunk://#diff-d79e3cdb6e33c369b425bd82366374a092ce7036bfb11525016aa226ed51806fR1-R67): Created the `TabContext` and `TabProvider` for managing the state of selected tabs across the application.
* …

Implement linked tabs component and update react query configuration

---

docs/pages/configuration.mdx

Update `cacheTime` to `gcTime`
This key was renamed in v5 of React Query
https://tanstack.com/query/latest/docs/framework/react/guides/migrating-to-v5#rename-cachetime-to-gctime

docs: Update configuration example for React Query

---

docs/pages/postgrest/getting-started.mdx

Add `LinkedTabs` to differentiating what `supabase-cache-helpers` package to install for swr and react-query

docs: update postgrest getting start docs
